name: cipher
author: Iván Zaera Avellón <izaera@gmail.com>
version: 0.5.1
homepage: http://izaera.github.io/cipher/
description: A Dart library implementing cryptographic algorithms.
documentation: http://izaera.github.io/cipher/api/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  bignum: 0.0.4
  fixnum: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
