name: cipher
version: 0.3.0
author: Iván Zaera Avellón <izaera@gmail.com>
description: A Dart library for encryption and decryption.
homepage: http://izaera.github.io/cipher/
documentation: http://izaera.github.io/cipher/doc/
dependencies:
  fixnum: 0.8.7
dev_dependencies:
  unittest: 0.8.7
