name: cipher
version: 0.2.0
author: Iván Zaera Avellón <izaera@gmail.com>
description: A Dart library for encryption/decryption mainly based on Bouncy Castle Java library.
homepage: http://izaera.github.io/cipher/
dependencies:
  fixnum: 0.8.1
  meta: 0.7.3+1
dev_dependencies:
  unittest: 0.7.3+1
