name: pointycastle
version: 0.10.0-dev
author: The Pointy Castle team
description: A Dart library implementing cryptographic algorithms.
homepage: http://pointycastle.github.io/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
#documentation: http://pointycastle.github.io/docs/
dependencies:
  bignum: '>=0.0.5 <0.1.0'
  fixnum: '>=0.9.0 <0.10.0'
  logging: '>=0.11.0 <0.12.0'
  reflectable: '>=0.5.1 <0.6.0'
  quiver_collection: '>=1.0.0 <2.0.0'
  quiver_pattern: '>=1.0.0 <2.0.0'
dev_dependencies:
  benchmark_harness: '>=1.0.4 <2.0.0'
  browser: '>=0.9.0 <0.10.0'
  matcher: '>=0.12.0 <0.13.0'
  test : '>=0.12.7 <0.13.0'

transformers:
- reflectable:
    entry_points:
      - test/adapters/stream_cipher_as_block_cipher_test.dart
      - test/asymmetric/pkcs1_test.dart
      - test/asymmetric/rsa_test.dart
      - test/block/aes_fast_test.dart
      - test/digests/md2_test.dart
      - test/digests/md4_test.dart
      - test/digests/md5_test.dart
      - test/digests/ripemd128_test.dart
      - test/digests/ripemd160_test.dart
      - test/digests/ripemd256_test.dart
      - test/digests/ripemd320_test.dart
      - test/digests/sha1_test.dart
      - test/digests/sha3_test.dart
      - test/digests/sha224_test.dart
      - test/digests/sha256_test.dart
      - test/digests/sha384_test.dart
      - test/digests/sha512_test.dart
      - test/digests/sha512t_test.dart
      - test/digests/tiger_test.dart
      - test/digests/whirlpool_test.dart
      - test/key_derivators/pbkdf2_test.dart
      - test/key_derivators/scrypt_test.dart
      - test/key_generators/ec_key_generator_test.dart
      - test/key_generators/rsa_key_generator_test.dart
      - test/macs/hmac_test.dart
      - test/modes/cbc_test.dart
      - test/modes/cfb_test.dart
      - test/modes/ecb_test.dart
      - test/modes/gctr_test.dart
      - test/modes/ofb_test.dart
      - test/modes/sic_test.dart
      - test/paddings/padded_block_cipher_test.dart
      - test/paddings/pkcs7_test.dart
      - test/random/auto_seed_block_ctr_random_test.dart
      - test/random/block_ctr_random_test.dart
      - test/random/fortuna_random_test.dart
      - test/signers/ecdsa_signer_test.dart
      - test/signers/rsa_signer_test.dart
      - test/src/ufixnum_test.dart
      - test/stream/salsa20_test.dart
      - test/test/asymmetric_block_cipher_tests.dart
      - test/test/block_cipher_tests.dart
      - test/test/digest_tests.dart
      - test/test/key_derivators_tests.dart
      - test/test/key_generators_tests.dart
      - test/test/mac_tests.dart
      - test/test/padding_tests.dart
      - test/test/registry_tests.dart
      - test/test/signer_tests.dart
      - test/test/stream_cipher_tests.dart
      - test/impl_test.dart
- test/pub_serve:
    $include: test/**_test.dart