name: cipher
version: 0.0.2
author: Iván Zaera Avellón <izaera@gmail.com>
description: |-
  A Dart library for encryption/decryption mainly based on Bouncy Castle Java library. Implementation for most used standard crypto algorithms (AES, Salsa20, CTR, ...) are provided.

  Most of the classes are ports of Bouncy Castle from Java to Dart. Tests and benchmarks for every algorithm are also provided.
homepage: http://izaera.github.io/cipher/
dependencies:
  meta: 0.7.3+1
dev_dependencies:
  unittest: 0.7.3+1
