name: cipher
version: 0.0.1
author: Iván Zaera Avellón <izaera@gmail.com>
description: |-
  A Dart library for encryption/decryption mainly based on Bouncy Castle Java library. Most of the classes are ports of Bouncy Castle from Java to Dart. The porting is almost always direct except for some classes that had been added to ease the use of low level data.

  Tests and benchmarks for every algorithm are also provided. The expected results for the tests are computed with the Bouncy Castle Java version and matched against the results got from Dart.
homepage: https://github.com/izaera/cipher
dependencies:
  meta: 0.7.3+1
dev_dependencies:
  unittest: 0.7.3+1
