name: pointycastle
version: 0.7.0
author: Iván Zaera Avellón <izaera@gmail.com>
description: A Dart library implementing cryptographic algorithms.
homepage: http://pointycastle.github.io/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://pointycastle.github.io/docs/
dependencies:
  bignum: '>=0.0.5 <0.1.0'
  fixnum: '>=0.9.0 <0.10.0'
  logging: '>=0.11.0 <0.12.0'
  reflectable: '>=0.5.1 <0.6.0'
  quiver_collection: '>=1.0.0 <2.0.0'
  quiver_pattern: '>=1.0.0 <2.0.0'
dev_dependencies:
  benchmark_harness: '>=1.0.4 <2.0.0'
  browser: '>=0.9.0 <0.10.0'
  matcher: '>=0.12.0 <0.13.0'
  test : '>=0.12.7 <0.13.0'
